# Generated by Django 5.1.3 on 2025-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
